apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ubuntu
    command: ["sleep2.0"] # Overrides ENTRYPOINT
    args: ["10"] # Overrides CMD in Dockerfile
    # env:
    #   - name: APP_COLOR
    #     value: pink
    #   - name: APP_COLOR2
    #     valueFrom:
    #       configMapKeyRef:
    #         name: configmap
    #         key: color2
    #   - name: APP_COLOR3
    #     valueFrom:
    #       secretKeyRef:
    #         name: secret
    #         key: color3
    envFrom:
      - configMapRef:
          name: myconfigmap
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumes:
      - name: app-config-volumes
        configMap:
          name: my-config
