apiVersion: apps/v1
kind: DaemonSet # Similar to replicaset
metadata:
  name: monitoring-agent
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec: 
      containers:
        - name: monitoring-agent
          image: monitoring-agent