# Deployment has rollback/rolling updates
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-rs
  labels:
    app: my-app-rs
    env: stage
spec:
  replicas: 3
  strategy:
    type: Recreate # RollingUpdate (default)
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: front-end
    containers:
      - image:  nginx
        name:  nginx
  selector:
    matchLabels:
      app: my-app-rs