apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: default
  labels:
    name: myapp-pod
spec:
  # nodeName: node02
  # tolerations:
  #   - key: "app"
  #     operator: "Equal"
  #     value: "blue"
  #     effect: "NoSchedule"
  # schedulerName: custom-scheduler
  initContainers:
    - name: pull-code
      image: busybox
      command: ["sh", "-c", "git clone repo; done;"]
  containers:
  - name: myapp-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: acnd
      - secretRef:
          name: abcd
  # nodeSelector:
  #   size: Large 
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: size
  #             operator: In
  #             values:
  #             - Large
  #             - Medium
              # - key: size
              #   operator NotIn
              #   values:
              #   - Small