apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
spec:
  replicas: 3
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx
          ports:
            - containerPort: 80
