kind: Service
apiVersion: v1
metadata:
  name:  svc1
spec:
  selector:
    app:  demo
    type: front-end
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  8080
    nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 80
